version: "3.9"
services:
  database:
    image: postgres
    env_file:
      - .env
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/rails
      - /bundle
    ports:
      - "3000:3000"
    depends_on:
      - database
