source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.7.7"

gem "rails", "~>7.0.4"
gem "image_processing", "~>1.9.3"
gem "mini_magick", "~>4.9.5"
gem "active_storage_validations", "~>0.8.2"
gem "bcrypt", "~> 3.1.13"
gem "faker", "~>2.1.2"
gem "will_paginate", "~>3.1.8"
gem "bootstrap-will_paginate", "~>1.0.0"
gem "bootstrap-sass", "~>3.4.1"
gem "puma", "~>5.6.5" # (was 3.12.2)
gem "dartsass-rails", "~>0.4.1"
gem "jbuilder", "~>2.11.5" # (was 2.9.1)
gem "bootsnap", "~>1.15.0", require: false # (was 1.4.5)
gem "sprockets-rails"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "net-http"

group :development, :test do
  gem "sqlite3", "~> 1.5.4" # (was 1.4.1)
  gem "byebug", "~>11.0.1", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  gem "web-console", "~>4.2.0" # (was 4.0.1)
  gem "listen"
  gem "spring", "~>2.1.0"
  gem "spring-watcher-listen", "~>2.0.1"
end

group :test do
  gem "capybara", "~>3.28.0" # (was 3.38.0)
  gem "selenium-webdriver", "~>4.7.1" # (was 3.142.4)
  gem "webdrivers", "~>5.2.0" # (was 4.1.2)
  gem "rails-controller-testing", "~>1.0.4"
  gem "minitest", "~>5.11.3"
  gem "minitest-reporters", "~>1.5.0" # (was 1.3.8)
  gem "guard", "~>2.15.0"
  gem "guard-minitest", "~>2.4.6"
end

group :production do
  gem "pg", "~>1.1.4"
  gem "aws-sdk-s3", "1.46.0", require: false
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]