source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.3'

gem 'active_storage_validations', '~>0.8.2'
gem 'bcrypt', '~> 3.1.13'
gem 'bootsnap', '~>1.15.0', require: false
gem 'faker', '~>2.1.2'
gem 'image_processing', '~>1.9.3'
gem 'jbuilder', '~>2.11.5'
gem 'mini_magick', '~>4.9.5'
gem 'net-http', '~> 0.3.2'
gem 'puma', '~>5.6.5'
gem 'rails', '~>7.0.4'
gem 'sprockets-rails', '~> 3.4', '>= 3.4.2'
gem 'importmap-rails', '~> 1.1', '>= 1.1.5'
gem 'stimulus-rails', '~> 1.2', '>= 1.2.1'
gem 'turbo-rails', '~> 1.3', '>= 1.3.2'
gem 'will_paginate', '~>3.1.8'
gem 'bootstrap-sass', '~> 3.4', '>= 3.4.1'
gem 'bootstrap-will_paginate', '~>1.0.0'

group :development, :test do
  gem 'byebug', '~>11.0.1', platforms: %i[mri mingw x64_mingw]
  gem 'rubocop'
  gem 'rubocop-minitest'
  gem 'rubocop-rails'
  gem 'sqlite3', '~> 1.5.4'
end

group :development do
  gem 'listen', '~> 3.7', '>= 3.7.1'
  gem 'spring', '~>2.1.0'
  gem 'spring-watcher-listen', '~>2.0.1'
  gem 'web-console', '~>4.2.0'
end

group :test do
  gem 'capybara', '~>3.38.0'
  gem 'guard', '~>2.15.0'
  gem 'guard-minitest', '~>2.4.6'
  gem 'minitest', '~>5.11.3'
  gem 'minitest-reporters', '~>1.5.0'
  gem 'rails-controller-testing', '~>1.0.4'
  gem 'ruby_gntp', '~> 0.3.4'
  gem 'selenium-webdriver', '~>4.7.1'
  gem 'webdrivers', '~>5.2.0'
end

group :production do
  gem 'aws-sdk-s3', '1.46.0', require: false
  gem 'pg', '~>1.1.4'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
